// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLq8Flq6E-qEmo-CxQ3hXxv0ugEGoIYVY',
    appId: '1:325419873872:web:16feb53629493a22ca4355',
    messagingSenderId: '325419873872',
    projectId: 'facebook-f409d',
    authDomain: 'facebook-f409d.firebaseapp.com',
    storageBucket: 'facebook-f409d.firebasestorage.app',
    measurementId: 'G-WFSL83FFQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBRVvu3zCxyxa3LwCPwzhIB6VW9VAafAk',
    appId: '1:325419873872:android:ea52631cb953efd4ca4355',
    messagingSenderId: '325419873872',
    projectId: 'facebook-f409d',
    storageBucket: 'facebook-f409d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBakiXzgjfH3EFDw_XM_F2ME1RBXOlSVYg',
    appId: '1:325419873872:ios:0cee33b6b2e2808aca4355',
    messagingSenderId: '325419873872',
    projectId: 'facebook-f409d',
    storageBucket: 'facebook-f409d.firebasestorage.app',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBakiXzgjfH3EFDw_XM_F2ME1RBXOlSVYg',
    appId: '1:325419873872:ios:0cee33b6b2e2808aca4355',
    messagingSenderId: '325419873872',
    projectId: 'facebook-f409d',
    storageBucket: 'facebook-f409d.firebasestorage.app',
    iosBundleId: 'com.example.facebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLq8Flq6E-qEmo-CxQ3hXxv0ugEGoIYVY',
    appId: '1:325419873872:web:d8a3d3ec6678dd77ca4355',
    messagingSenderId: '325419873872',
    projectId: 'facebook-f409d',
    authDomain: 'facebook-f409d.firebaseapp.com',
    storageBucket: 'facebook-f409d.firebasestorage.app',
    measurementId: 'G-G8GTYR3VPR',
  );

}